### ISSUE TITLE
The item selected display incorrectly after close the PhoneGap Build Projects dialog

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-phonegap#10]
Steps:
1. Launch the Brackets and log in the phonegap
2. Click "PhoneGap">"Link with PhoneGap Build Project"
3. Select an other item
4. Click "X" on the upper right corner.(Not save the change)
5. Click "PhoneGap">"Link with PhoneGap Build Project" again, check the selected item
6. Click "PhoneGap">"Send Files to PhoneGap Build"

Problem:
step5: The selected item should not be changed and display the original one, but actually, the selected item is the changed one.
step6:  Although the selected one display the changed one, the files send to the original one.

Env: Win7; Win8; Mac
Language: ENU
Build: 3883 with latest phonegap package

Screenshot:
https://www.dropbox.com/s/ialfsmdce09riki/ReproduceStep.zip

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
