### ISSUE TITLE
ArrayBuffer values are deprecated in Blob Constructor

### ISSUE THREAD

**Issue by ryanstewart** [adobe/brackets-phonegap#32]
I get this warning when I upload a new project:

ArrayBuffer values are deprecated in Blob Constructor. Use ArrayBufferView instead

We should look into using ArrayBufferView.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
