### ISSUE TITLE
Panel should be resizable

### ISSUE THREAD

**Issue by gruehle** [adobe/brackets-phonegap#38]
Brackets added support for panel resizing in Sprint 16. 

To make the panel resizable:
1. Add the following classes to the panel div: `"vert-resizable top-resizer"`
2. Add `var Resizer = brackets.getModule("utils/Resizer")`
3. After the panel is created and added, call `Resizer.makeResizable($panel.get(0), "vert", "top", 100, false)`
   (100 is the min height--feel free to adjust as needed)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
