### ISSUE TITLE
[French] The cancel button is not localized

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-phonegap#39]
Steps:
1. Launch the Brackets
2. Log in the PhoneGap
3. Select a project and click the delete button

Result: The button on the warning message is not localized
Expect: The button on the warning message is localized
Please refer to the screenshot:
https://www.dropbox.com/s/oyssdoxvz5ti8zl/CancelButton.jpg?m

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
