### ISSUE TITLE
The page you were looking for doesn't exist when click App name in Brackets.

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-phonegap#4]
1. Sign out from PhoneGap website
2. Launch Brackets and click PhoneGap icon
3. sign in from Brackets
4. Link with PhoneGap Build Project
5. Click the Project name in PhoneGap panel
6. The page you were looking for doesn't exist

Expected: hint for sign in on the website but not receive a page of doesn't exist

Env: MacOS X 10.6/7/8 and Windows 7/8
Lang: English
build: 3797 with latest phonegap package

Screenshot:
https://www.dropbox.com/s/iu7q72xja76gdxx/PhoneGap_WebPageNotExist.jpg

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
