### ISSUE TITLE
[French] The warning message about the email address is not localized

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-phonegap#40]
Steps:
1. Launch the Brackets
2. Click the PhoneGap icon to open the PhoneGap build panel
3. Input some characters but not a email format

Result: The strings on warning message is not localized
Expect: The strings on warning message is localized
Please refer to the screenshot:
https://www.dropbox.com/s/4g0l7gg3lq2k9mg/NoEmailAddress.jpg?m

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
