### ISSUE TITLE
Can not locate the cursor on the password field use mouse

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-phonegap#41]
Steps:
1.Launch the Brackets
2.Click the PhoneGap icon to open the PhoneGap build panel
3. Click the password field

Result: Can not locate the cursor on the password field use mouse, and must use the tab key to move the cursor to the password field
Expect: The cursor can be locate in the password field use nouse and input the password

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
