### ISSUE TITLE
There are some garbage characters on the panel if use the surrogate or 4 bytes character as the project name. 

### ISSUE THREAD

**Issue by Zhanxin** [adobe/brackets-phonegap#42]
Steps:
1. Launch the Brackets and login the PhoneGap build
2. Click "PhoneGap" > "Create new PhoneGap Build project"
3. Input some surrogate or 4 bytes characters as the project name

Result: There are some garbage characters display on the PhoneGap Build panel
Expect: There are no garbage characters display on the PhoneGap Build panel
Please refer to screenshot:
https://www.dropbox.com/s/6b8def43c80zffc/GarbageInName.jpg?m
This issue reproduce on CN, JA env.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
