### ISSUE TITLE
Not Able to Access Password Field

### ISSUE THREAD

**Issue by stphnwlkr** [adobe/brackets-phonegap#44]
Just installed this plugin in Edge Code and could not access the password field.  After reviewing the change history I saw the change to the z-index for the password field (#31).  I removed the z-index from #pgb-password and it resolved the issue.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
