### ISSUE TITLE
[Core]: There is a layout problem with the message displaying on the top of the code panel.

### ISSUE THREAD

**Issue by dil77307** [adobe/brackets-phonegap#48]
Problem:
The message display with layout problem on the top of code panel.
Some part of the string is cut off.

Step:
1. Launch Brackets
2. Install the Phonegap build extension
3. Click on Phonegap icon
4. Input the correct username and password, click login
5. Check the pop up message 

Result:
 There is layout problem with the pop up message.

Expect:
The pop up message should be displayed without any layout problem.

Build info:
Win7: Sprint24_7033
Mac:  Sprint24_7037

Screenshot:
Win7:
![Brackets_PGB_LayoutIssue_Win7_24_7033](https://f.cloud.github.com/assets/3336842/418932/33ff157e-acbc-11e2-91cc-4b44daa1880d.jpg)
Mac:
![Brackets_PGB_LayoutIssue_Mac_24_7037](https://f.cloud.github.com/assets/3336842/418937/3d7260de-acbc-11e2-8a1f-2bf4729c982e.jpg)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
