### ISSUE TITLE
[Core]: The error message does not meet the behavior when delete the PhoneGap build while rebuilding.

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-phonegap#49]
Method:
1. Launch Brackets and install PGB extension
2. Login the Phonegap
3. Click "Rebuild" button 
4. While the build is rebuilding, click "Delete" button
5. Click OK on the top message
6. Observe there will pop up an error message.
Result: The error message indicates login failed
Expected: The error message if any should meet the behavior

Build: sprint24 7202
Env: Windows7 & MacOSX English

Screenshot:
![Rebuilding and Delete-Wrong error message-ENU](https://f.cloud.github.com/assets/2245172/435183/5e23f57a-afac-11e2-970f-6ec7bf56f9ad.png)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
