### ISSUE TITLE
Link with PhoneGap Build Project dialog window layout incorrect

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-phonegap#5]
1. Launch Brackets
2. Click in PhoneGap menu
3. Click Link with PhoneGap Build Project

Env: Mac only MacOS X 10.6/7/8
Lang: English
Build: 3797 with latest phonegap package

Screenshot
https://www.dropbox.com/s/9oul8zqe1bmmpn0/PhoneGap_LinkWithPhoneGapBuild.jpg

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
