### ISSUE TITLE
Brackets 28 + PhoneGap white screen on rebuild

### ISSUE THREAD

**Issue by afwd** [adobe/brackets-phonegap#52]
Hi, 

When I rebuild an application using the extension I get a white screen within the Brackets application. The menu bar is still usable, but the rest of the application is just flat white a constant loading / working mouse pointer on hover.

Simon

**Comment by sagarhiremath6** [comment]
Please let me know what solution you guys got in order to fix this issue.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
