### ISSUE TITLE
Avoid using low-level brackets.fs APIs

### ISSUE THREAD

**Issue by peterflynn** [adobe/brackets-phonegap#55]
I noticed that the PhoneGap extension uses several low-level (non "public") Brackets APIs for file IO. Sine they can change without warning, it would be better to use the higher level "official" APIs:
- `brackets.fs.readdir()` -> `FileSystem.getDirectoryForPath().getContents()`
- `brackets.fs.stat()` -> `FileSystem.resolve()`

(Note: we just introduced a new, cleaner file API in Brackets Sprint 34. The suggestions above are based on that API. If an update was released using the Sprint 34+ APIs, users with Sprint 33 would still be able to download the older version of this extension that doesn't require Sprint 34).

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
