### ISSUE TITLE
[Core][PhoneGap Build panel]: The PhoneGap build panel cannot be closed. 

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-phonegap#57]
Steps:
1. Download PhoneGap extension from this URL: https://github.com/adobe/brackets-phoneGap
2. Launch Brackets and click Help > Show Extensions Folder.
3. Unzip the download zip file PhoneGap and copy it into the `extensions/user` folder.
4. Reload Brackets and click the PhoneGap extension icon on the right side bar.
5. Click the close icon on the PhoneGap Build panel.
6. Sign in with an Adobe ID.
7. Repeat step 5.

Result:
At step5 and step7, the PhoneGap Build panel cannot be closed. I have to reload Brackets to close the panel.

Expected:
The panel should be closed when user click the close button.

ENV: MAC 10.9 and Win8.1 English OS
Build:  0.34.0-10631(Mac) and 0.34.0-10534 (Win)

Notes: This issue also reproduces for sprint31. And this issue also not reproduces if I install this extension from Brackets Available extensions library (which is 0.1.0 version brackets-phonegap).

Snapshots:
Here are snapshots for details:
![screen shot 2013-11-11 at 9 22 22 pm](https://f.cloud.github.com/assets/4251563/1519386/33064b80-4b5c-11e3-9bb3-05dbc39d8bb3.png)
![screen shot 2013-11-11 at 9 24 23 pm](https://f.cloud.github.com/assets/4251563/1519387/3da6860e-4b5c-11e3-9632-8641d0434378.png)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
