### ISSUE TITLE
[Core][PhoneGap Build panel]: There is no scrollbar on the PhoneGap Build panel even if there are many projects.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-phonegap#58]
Steps:
1. Download PhoneGap extension from this URL: https://github.com/adobe/brackets-phoneGap
2. Launch Brackets and click Help > Show Extensions Folder.
3. Unzip the download zip file PhoneGap and copy it into the extensions/user folder.
4. Reload Brackets and click the PhoneGap extension icon on the right side bar.
5. Sign in with an Adobe ID and make sure there are many builds , if not , new some builds.
6. Resize the height of the panel and observe.

Result:
There is no scrollbar on the panel, so some builds cannot be found from the panel.

Expected:
There should be scrollbar on the panel if there are many builds.

ENV: MAC 10.9 and Win8.1 English OS
Build: 0.34.0-10631(Mac) and 0.34.0-10534 (Win)

Notes: 
 This issue not reproduces if I install this extension from Brackets Available extensions library (which is 0.1.0 version brackets-phonegap).

Snapshots:
Please refer to snapshots for details:
![scroll bar](https://f.cloud.github.com/assets/4251563/1519807/1fc21462-4b6d-11e3-9239-7b5016c63f9c.png)
0.1.0 version  reference:
![1 0 reference](https://f.cloud.github.com/assets/4251563/1519886/f6781a1e-4b6e-11e3-9930-c85933105936.png)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
