### ISSUE TITLE
[L10N][French][Cancel Button on dialog]: Button Cancel is unlocalized on Delete PhoneGap Build Project dialog.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-phonegap#59]
Steps:
1. Download PhoneGap extension from this URL: https://github.com/adobe/brackets-phoneGap
2. Launch Brackets and click Help > Show Extensions Folder.
3. Unzip the download zip file PhoneGap and copy it into the extensions/user folder.
4. Reload Brackets and click the PhoneGap extension icon on the right side bar.
5. Sign in with an Adobe ID.
6. Select one project which you want to delete, then click the Button Delete.

Result:
On the dialog, the button Cancel is unlocalized.

Expected:
This button should be localized in French.

Notes:
This also reproduces for "New PhoneGap Build Project" ,"PhoneGap Build Projects" and "Send Files to PhoneGap Build" dialog.

ENV: MAC 10.9 French OS
Build: 0.34.0-10631

Snapshots:
Please refer to snapshots for details:
![fr-2](https://f.cloud.github.com/assets/4251563/1520106/0af91070-4b73-11e3-87cc-5f69cfd8f341.png)
ENU for reference:
![en-2](https://f.cloud.github.com/assets/4251563/1520125/b2a80088-4b73-11e3-95d6-a5a6abbe389e.png)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
