### ISSUE TITLE
Cancel button rendered incorrectly

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-phonegap#6]
1. Launch Brackets
2. Click in PhoneGap menu
3. Click Send Files to PhoneGap Build
4. 'Are you sure....' dialog pops up
5. Mouse move on Cancel button

Env: MacOS X 10.6/7/8 and Windows 7/8
Lang: English
build: 3797 with latest phonegap package

Screenshot
https://www.dropbox.com/s/swiidgwlwtlkssg/PhoneGap_CancelButton.jpg

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
