### ISSUE TITLE
[Core][Installation]: Cannot install Phonegap extension by URL successfully.

### ISSUE THREAD

**Issue by julieyuan** [adobe/brackets-phonegap#61]
Steps:
1. Launch Brackets.
2. Click Extension Manager icon to bring up Extension Manager dialog.
3. Click tab Installed, then click Install from URL and input into bar: https://github.com/adobe/brackets-phonegap
4. Then click button install.

Result:
The installation failed and it says SyntaxError.

Expected:
It should install phonegap extension successfully.

Notes:
phonegap extension can be installed by inputing the folder into user extension folder.

ENV: MAC 10.9 and Win7 (x64) English OS
Build: 0.35.0-10746 

Snapshots:
Please refer to snapshot for details:
![capture decran 2013-11-25 a 10 56 40 pm](https://f.cloud.github.com/assets/4251563/1620038/3639979e-566a-11e3-9628-f1c78eab4976.png)

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
