### ISSUE TITLE
Possible encoding issue with PGB send?

### ISSUE THREAD

**Issue by mobunti** [adobe/brackets-phonegap#76]
Hi

Ive just started using Brackets on windows 8 and linux  and installed your phonegap plugin immediately. Top plugin. 

When I send to PGB from the plugin, PGB compiles but the app runs on my phone and just shows a blank black screen, yet when i zip up the files outside of brackets and send them to PGB it compiles and works fine. I think I may have tracked down the issue to my config.xml having an 8859-1 encoding, which PGB seems to be fine with directly but maybe when  it goes through your plugin something is being converted and maybe is causing an issue with the xml? Anyway, now Ive found the problem, Ive got the file saved as utf8 and the plugin is fine now, but weird how i can upload a zip to PGB and it works with a non utf8 encoding, when I guess that's all you are doing too.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
