### ISSUE TITLE
Sending Files to PhoneGap Build Breaks the Enconding UTF-8 Latin Characters

### ISSUE THREAD

**Issue by FenixAzul** [adobe/brackets-phonegap#78]
When trying to push changes to the _Adobe PhoneGap Build_ the application ends giving squares on all special latin characters. If I manually zip and upload them it works perfectly.

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
