### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by filmaj** [adobe/brackets-phonegap#82]
Hello @adobe/brackets and @adobe/brackets-admin teams!
My name is Fil and I’m from Adobe’s Open Source Office. I see this project has been inactive for a long time. Just wondering: is there still value in keeping this project around? Do we foresee community usage/activity happening around this project? Obviously this repo has community activity with its open issues and pull requests, but I'm not sure how much effort the project team is putting in to actually nurture the community. I'm trying to gauge that with this issue.

If yes, can I send some pull requests to update the documentation? At a minimum we need contribution guidelines that reference requiring the signing of [Adobe’s CLA](http://opensource.adobe.com/cla.html).

If no, is it OK if we archive this project? Or perhaps we would want to move it to e.g. github.com/phonegap? (cc @alharding / @purplecabbage)

Thanks for any info.

-Fil

**Comment by filmaj** [comment]
These same questions apply to this related (but forked) project: https://github.com/adobe/brackets-phonegap-prototype

**Comment by purplecabbage** [comment]
This seems like a duplicate of #79 ?

**Comment by filmaj** [comment]
This is not active - will archive it.
