### ISSUE TITLE
Incorrect behave for sending files when there are files under editing

### ISSUE THREAD

**Issue by Zhuyun** [adobe/brackets-phonegap#9]
1. Launch Brackets
2. Login PhoneGap in Brackets
3. Link with PhoneGap sample project
4. Open a folder with some files in Brackets
5. Open and modify some files in the folder
6. Leave those files under editing
7. Click PhoneGap > Send Files to PhoneGap Build
8. Files sent to back end and finish rebuild without any warning message for the not saving files

Expected: there should be some messages to notice user to save before sending or sending without saving

Env: MacOS X 10.6/7/8 and Windows 7/8
Lang: English
Build: 3797 with latest phonegap package

**Comment by filmaj** [comment]
Sorry, this project has not been maintained since 2014. As a result, we will archive the project. If anyone feels like reviving it, feel free to fork it!
